"""
main.py — FastAPI application for the LearnForge AI Customer Support Assistant.

Endpoints
─────────
POST   /chat                        — Main chat endpoint (RAG pipeline)
GET    /sessions/{session_id}       — Fetch conversation history
DELETE /sessions/{session_id}       — Clear a session
POST   /admin/reingest              — Re-run knowledge-base ingestion
GET    /health                      — Health check

Session storage
───────────────
For this prototype, sessions are stored in an in-process dict keyed by
session_id (UUID generated by the client).  In production this should
be replaced with Redis or a persistent session store.
"""

from __future__ import annotations

import subprocess
import sys
from collections import defaultdict
from contextlib import asynccontextmanager

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from models import (
    ChatRequest,
    ChatResponse,
    IngestResponse,
    Message,
    SessionHistoryResponse,
)
from rag import run_rag

load_dotenv()

# ---------------------------------------------------------------------------
# In-process session store  {session_id: [Message, ...]}
# ---------------------------------------------------------------------------

_sessions: dict[str, list[Message]] = defaultdict(list)

# ---------------------------------------------------------------------------
# App lifecycle
# ---------------------------------------------------------------------------


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Validate vector store is ready on startup
    try:
        from rag import _store  # noqa: F401

        print(f"[OK] Vector store loaded — {_store.count()} chunks ready.")
    except RuntimeError as exc:
        print(f"[ERROR] {exc}")
        print("    Run: python ingest.py  — then restart the server.")
    yield


# ---------------------------------------------------------------------------
# App + CORS
# ---------------------------------------------------------------------------

app = FastAPI(
    title="LearnForge AI Support API",
    description="RAG-powered customer support assistant for LearnForge ed-tech.",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:5174",
        "http://127.0.0.1:5174",
    ],
    allow_origin_regex=r"http://(localhost|127\.0\.0\.1)(:\d+)?",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


@app.get("/health", tags=["system"])
async def health():
    """Simple liveness probe."""
    return {"status": "ok", "service": "learnforge-ai-support"}


@app.post("/chat", response_model=ChatResponse, tags=["chat"])
async def chat(request: ChatRequest) -> ChatResponse:
    """
    Main chat endpoint.

    - Appends the user message to the session history.
    - Runs the RAG pipeline (retrieval + Gemini generation).
    - Appends the assistant reply to the session history.
    - Returns the full ChatResponse including sources + escalation flag.
    """
    session_id = request.session_id
    user_message = request.message.strip()

    if not user_message:
        raise HTTPException(status_code=400, detail="Message cannot be empty.")

    # Retrieve existing history (excludes the current turn)
    history = _sessions[session_id]

    # Run the full RAG pipeline
    response: ChatResponse = run_rag(
        query=user_message,
        session_id=session_id,
        history=history,
    )

    # Persist both turns to session history
    _sessions[session_id].append(Message(role="user", content=user_message))
    _sessions[session_id].append(Message(role="assistant", content=response.answer))

    return response


@app.get("/sessions/{session_id}", response_model=SessionHistoryResponse, tags=["sessions"])
async def get_session(session_id: str) -> SessionHistoryResponse:
    """Return the full conversation history for a session."""
    if session_id not in _sessions:
        raise HTTPException(status_code=404, detail="Session not found.")
    return SessionHistoryResponse(
        session_id=session_id,
        messages=_sessions[session_id],
    )


@app.delete("/sessions/{session_id}", tags=["sessions"])
async def delete_session(session_id: str):
    """Clear the conversation history for a session (start fresh)."""
    if session_id not in _sessions:
        raise HTTPException(status_code=404, detail="Session not found.")
    del _sessions[session_id]
    return {"status": "deleted", "session_id": session_id}


@app.post("/admin/reingest", response_model=IngestResponse, tags=["admin"])
async def reingest() -> IngestResponse:
    """
    Re-run the knowledge-base ingestion pipeline.

    Useful when KB documents are updated (stale data handling).
    Runs ingest.py in a subprocess so it doesn't block the event loop.
    """
    try:
        result = subprocess.run(
            [sys.executable, "ingest.py"],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode != 0:
            raise HTTPException(
                status_code=500,
                detail=f"Ingestion failed:\n{result.stderr}",
            )

        # Parse chunk count from stdout (ingest.py prints "X chunks stored")
        import re

        match = re.search(r"(\d+) chunks stored", result.stdout)
        count = int(match.group(1)) if match else -1

        # Reload the vector store reference in rag.py
        import importlib

        import rag

        importlib.reload(rag)

        return IngestResponse(
            status="success",
            chunks_inserted=count,
            message=result.stdout.strip(),
        )
    except subprocess.TimeoutExpired:
        raise HTTPException(status_code=504, detail="Ingestion timed out.")
